name: Update widgets
on:
  schedule:
    - cron: "0 7 * * *"  # daily 07:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm i @octokit/rest

      - name: Generate SVG
        run: node scripts/generate-svg.js

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/*.svg
          git commit -m "chore: update widgets" || echo "nothing to commit"
          git push
